### PR TITLE
#39: [description] `description` should be optional (closes #39)

### LINKED ISSUE #39: [description] `description` should be optional
## description
Annotating a case class, in `@param <name> <description>`, `<description>` should be optional

looks like currently it is not

## how to reproduce
this commit on LOL fixes it changing the api annotations https://github.omnilab.our.buildo.io/buildo/aliniq/pull/2585/commits/dbc9b94eb00862bc2a6e27e575103ae81d3e797e

### PR DESCRIPTION
**Pull request by gabro**
Issue #39

### CODE REVIEW

**Comment by giogonzo** [comment]
tested on LOL, 👍 👍 👍

**Comment by utaal** [comment]
I don't get this. Can't one just leave out the `@param` line when they don't want to provide a description? What does having the `@param name` there buy you?

**Comment by giogonzo** [comment]
Uhm, I kind of took for granted that without the `@param` annotation metarpheus can't discover the param in question - if this is not the case, yes probably you're right

On another level, we might want to avoid situations where only a few params are annotated (it would be misleading reading through the code I think), but this is another story

**Comment by gabro** [comment]
On `@pathParam` it's useful since they're positional.

On `@param` it is debatable, but there are intermediate cases in which you don't have provided a meaningful description yet, but you still want to leave a placeholder.

This was the case on QIA, for instance.

Generally speaking, I'd metarpheus to be fairly permissive on the input, as long as it can make it fit into its structure.

**Comment by utaal** [comment]
👍

**Pull request merged**
